FROM jupyter/base-notebook
MAINTAINER Jan Kumor <elohhim@gmail.com>
LABEL Description="Docker image that contains Jupyter with a pre-compiled version of igraph's Python interface"
USER root
RUN echo 'Acquire::http::Proxy "http://192.168.129.20:8080/";' >> /etc/apt/apt.conf
RUN cat /etc/apt/apt.conf
RUN apt-get -y update
RUN apt-get -y install build-essential libxml2-dev zlib1g-dev python-dev python-pip pkg-config libffi-dev libcairo-dev
RUN apt-get -y install texlive texlive-latex-extra vim aspell
RUN apt-get -y install graphviz
RUN apt-get -y install libigraph0-dev
RUN pip install --proxy=http://192.168.129.20:8080 --upgrade pip
RUN pip install --proxy=http://192.168.129.20:8080 python-igraph
RUN pip install --proxy=http://192.168.129.20:8080 cairocffi
RUN pip install --proxy=http://192.168.129.20:8080 numpy
USER jovyan
